# Generated by Django 4.2.1 on 2023-06-01 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fréquentation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifiant_site', models.CharField(help_text="Entrez l'idendentifiant du site (e.g. 109)", max_length=200)),
                ('type_site', models.CharField(choices=[('E', 'Elémentaire'), ('M', 'Maternelle'), ('M/E', 'Mixte')], default='E', help_text='Entrez le type du site (e.g. E, M, M/E)', max_length=3)),
                ('date', models.TimeField(help_text='Entrez la date des repas (e.g. Science Fiction)')),
                ('prevision', models.IntegerField(help_text='Entrez le nombre de repas prévus (e.g. 31/05/2019)', null=True)),
                ('reel', models.IntegerField(help_text='Entrez le nombre de repas réellement consommés (e.g. 246)', null=True)),
                ('nom_site', models.CharField(help_text='Entrez le nom du site  (e.g. GAY LUSSAC)', max_length=200)),
                ('nom_site_syst', models.CharField(help_text='Entrez le nom Système du site  (e.g. GAY LUSSAC PRIM)', max_length=200)),
                ('prevision_syst', models.IntegerField(help_text='Enter a book genre (e.g. Science Fiction)', null=True)),
                ('reel_syst', models.IntegerField(help_text='Enter a book genre (e.g. Science Fiction)', null=True)),
                ('annee', models.IntegerField(help_text='Enter a book genre (e.g. 2019)')),
            ],
        ),
    ]
