# Generated by Django 4.2.1 on 2023-06-08 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cantinedata', '0002_remove_fréquentation_annee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fréquentation',
            name='date',
            field=models.DateTimeField(help_text='Entrez la date des repas (e.g. Science Fiction)'),
        ),
    ]
