# Generated by Django 4.2.1 on 2023-06-09 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cantinedata', '0003_alter_fréquentation_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fréquentation',
            name='date',
            field=models.DateField(help_text='Entrez la date des repas (e.g. Science Fiction)'),
        ),
    ]
