# Generated by Django 4.2.1 on 2023-06-18 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cantinedata', '0005_prediction_fréquentation_total_calcul_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fréquentation',
            name='total_calcul',
        ),
        migrations.RemoveField(
            model_name='fréquentation',
            name='total_manuel',
        ),
        migrations.RemoveField(
            model_name='fréquentation',
            name='total_modele',
        ),
        migrations.AddField(
            model_name='prediction',
            name='date',
            field=models.DateField(help_text='Entrez la date des repas (e.g. 2011-01-03)', null=True),
        ),
        migrations.AddField(
            model_name='prediction',
            name='total_calcul',
            field=models.IntegerField(help_text='Entrez le nombre total de repas tel que calculé (e.g. 246)', null=True),
        ),
        migrations.AddField(
            model_name='prediction',
            name='total_manuel',
            field=models.IntegerField(help_text='Entrez le nombre total de repas manuellement (e.g. 246)', null=True),
        ),
        migrations.AddField(
            model_name='prediction',
            name='total_modele',
            field=models.IntegerField(help_text='Entrez le nombre total de repas prédit par le modèle (e.g. 258)', null=True),
        ),
    ]
